[application]
name = "calculator"

[bundle]
identifier = "com.tatar"
publisher = "Tatar"
icon = [
  "assets/icon_resized_67bb655f65d46.png",
  "assets/icon.ico",
  "assets/icon.icns",
]

[web.app]

# HTML title tag content
title = "calculator"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
